const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const dict={
 en:{home:'Dashboard',lang:'Language',downloader:'Downloader',others:'Others',wa:'WhatsApp Channel',waDesc:'Official update channel, service notes, and important announcements.',report:'Report',reportDesc:'Tell us about broken links, failed downloads, or website errors.',heroTitle:'Fast media downloader with a clean modern dashboard.',heroDesc:'ClipNova helps you save supported media through a secure backend route. Choose a downloader, paste a link, select quality when available, then let the extractor process it.',start:'Start Downloading',openReport:'Report an Issue',available:'Available tools',maintenance:'Maintenance Mode',maintenanceDesc:'The service is temporarily unavailable while we improve the system.',back:'Back to Dashboard',send:'Send',name:'Name',email:'Email',message:'Message',namePh:'Enter your name',emailPh:'Enter your email',msgPh:'Explain the error or problem you experienced',url:'Media URL',urlPh:'Paste your link here',quality:'Quality',process:'Extracting media...',download:'Download / Extract',success:'Request completed.',failed:'Request failed.',tiktok:'Download TikTok videos through ClipNova backend with a clean extraction flow.',spotify:'Extract Spotify audio information and supported media using the configured API.',pinterest:'Download Pinterest images or videos from supported public links.',facebook:'Download Facebook videos from supported public posts or links.',instagram:'Download Instagram videos from supported public links.',ytmp4:'Download YouTube videos with selectable resolution.',ytmp3:'Download YouTube audio in MP3 format with selectable bitrate.'},
 id:{home:'Beranda',lang:'Bahasa',downloader:'Downloader',others:'Lainnya',wa:'Saluran WhatsApp',waDesc:'Saluran resmi untuk info update, status layanan, dan pengumuman penting.',report:'Report',reportDesc:'Laporkan link rusak, download gagal, atau error website.',heroTitle:'Downloader media cepat dengan dashboard modern dan rapi.',heroDesc:'ClipNova membantu menyimpan media yang didukung lewat backend aman. Pilih downloader, tempel link, pilih kualitas jika tersedia, lalu biarkan sistem mengekstrak.',start:'Mulai Download',openReport:'Laporkan Kendala',available:'Tools tersedia',maintenance:'Mode Maintenance',maintenanceDesc:'Layanan sedang tidak tersedia sementara karena sistem sedang diperbaiki.',back:'Kembali ke Beranda',send:'Kirim',name:'Nama',email:'Email',message:'Pesan',namePh:'Isi nama anda',emailPh:'Isi email anda',msgPh:'Isi kendala/error yang dialami',url:'URL Media',urlPh:'Tempel link di sini',quality:'Kualitas',process:'Sedang mengekstrak media...',download:'Download / Ekstrak',success:'Permintaan selesai.',failed:'Permintaan gagal.',tiktok:'Download video TikTok melalui backend ClipNova dengan proses ekstraksi yang rapi.',spotify:'Ekstrak audio Spotify dan media yang didukung menggunakan API yang dikonfigurasi.',pinterest:'Download gambar atau video Pinterest dari link publik yang didukung.',facebook:'Download video Facebook dari postingan atau link publik yang didukung.',instagram:'Download video Instagram dari link publik yang didukung.',ytmp4:'Download video YouTube dengan pilihan resolusi.',ytmp3:'Download audio YouTube format MP3 dengan pilihan bitrate.'}
};
function lang(){return localStorage.getItem('clipnova_lang')||'en'}function t(k){return (dict[lang()]||dict.en)[k]||k}
function applyLang(){document.documentElement.lang=lang();$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));$$('[data-i18n-placeholder]').forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang()))}
function toast(msg){let el=$('.toast')||document.body.appendChild(Object.assign(document.createElement('div'),{className:'toast'}));el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
window.addEventListener('load',()=>{setTimeout(()=>$('.loader')?.classList.add('hide'),450);applyLang();});
document.addEventListener('click',e=>{let b=e.target.closest('[data-toggle-sidebar]');if(b)$('#sidebar')?.classList.toggle('open');let l=e.target.closest('[data-lang]');if(l){localStorage.setItem('clipnova_lang',l.dataset.lang);applyLang();toast(l.dataset.lang==='id'?'Bahasa diganti ke Indonesia':'Language changed to English')}let m=e.target.closest('[data-modal]');if(m)$(m.dataset.modal)?.classList.add('show');let c=e.target.closest('[data-close-modal]');if(c)c.closest('.modal')?.classList.remove('show')});
async function postJSON(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok||j.ok===false)throw new Error(j.error||j.message||`HTTP ${r.status}`);return j}
window.handleDownload=async function(service,extra={}){const url=$('#url')?.value?.trim();const result=$('#result');if(!url)return toast(lang()==='id'?'URL wajib diisi':'URL is required');result.style.display='block';result.textContent=t('process');try{const data=await postJSON('/api/download',{service,url,...extra});result.textContent=JSON.stringify(data,null,2);toast(t('success'))}catch(e){result.textContent=e.message;toast(t('failed'))}}
window.handleReport=async function(){const name=$('#name').value.trim(),email=$('#email').value.trim(),message=$('#message').value.trim();if(!name||!email||!message)return toast(lang()==='id'?'Semua kolom wajib diisi':'All fields are required');$('#reportResult').style.display='block';$('#reportResult').textContent=lang()==='id'?'Mengirim report...':'Sending report...';try{await postJSON('/api/report',{name,email,message});$('#reportResult').textContent=lang()==='id'?'Report berhasil dikirim ke admin.':'Report sent to admin.';toast(t('success'))}catch(e){$('#reportResult').textContent=e.message;toast(t('failed'))}}
